

# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  name: Hosted VS2017

steps:
# Android
- task: CordovaBuild@1
  inputs:
    platform: 'android'
    configuration: '$(Configuration)'
    archs: 'android'
    cordovaVersion: '9.0.1'
    outputPattern: 'bin'
